controller_list:
  - name: /ros_control_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [joint_0,joint_1,joint_2,joint_3,joint_4,joint_5,joint_6]
